### ISSUE TITLE
Saving/loading too long paths causes crash in Avalonia

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/apollo-studio#325]
As reported by LaunchpadPhil. Maybe Windows7 specific?

```
Apollo Version: Version 1.3.1
Operating System: Microsoft Windows 6.1.7601 Service Pack 1

System.ArgumentException: Value does not fall within the expected range.
   at Avalonia.Win32.Interop.UnmanagedMethods.IShellItem.GetDisplayName(UInt32 sigdnName, IntPtr& ppszName)
   at Avalonia.Win32.SystemDialogImpl.GetAbsoluteFilePath(IShellItem shellItem)
   at Avalonia.Win32.SystemDialogImpl.<>c__DisplayClass1_0.<ShowFileDialogAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Avalonia.Controls.SaveFileDialog.ShowAsync(Window parent)
   at Apollo.Elements.Project.Save(Window sender, Boolean store) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Elements\Project.cs:line 175
   at Apollo.Elements.Project.Save(Window sender) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Elements\Project.cs:line 153
   at Apollo.Components.SaveButton.Click(PointerReleasedEventArgs e) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Components\SaveButton.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Apollo.Core.Program.Main(String[] args) in C:\Users\mat1jaczyyy\Desktop\apollo-studio\Apollo\Core\Program.cs:line 125
```

**Comment by mat1jaczyyy** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/3272
