### ISSUE TITLE
Crash when track with non-Launchpad port receives input from Preview

### ISSUE THREAD

**Issue by rpgaleksy** [mat1jaczyyy/apollo-studio#54]
### Description
Apollo crashes when a track with a non-Launchpad output receives input from a Preview device.

### To Reproduce
Open track with non-Launchpad output, insert Preview and trigger any note.

### Expected behavior
No crash.

### Screenshots
-

### Your setup
Windows 10 (1803)
Apollo Build 12 (0100506)

### Additional context
-

**Comment by rpgaleksy** [comment]
Tested on laptop without any MIDI device connected:
`Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Apollo.Structures.Signal.op_Equality(Signal a, Signal b) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Structures\Signal.cs:line 51
   at Apollo.Structures.Signal.Equals(Object obj) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Structures\Signal.cs:line 48
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValueInternal(TKey key, Int32 hashcode, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Apollo.Devices.Fade.MIDIEnter(Signal n) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Devices\Fade.cs:line 178
   at Apollo.Devices.Preview.MIDIEnter(Signal n) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Devices\Preview.cs:line 31
   at Apollo.DeviceViewers.PreviewViewer.PadChanged(Int32 index, Boolean state) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\DeviceViewers\PreviewViewer.cs:line 36
   at Apollo.DeviceViewers.PreviewViewer.PadPressed(Int32 index) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\DeviceViewers\PreviewViewer.cs:line 37
   at Apollo.Components.LaunchpadGrid.MouseEnter(Shape control, InputModifiers mods) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Components\LaunchpadGrid.cs:line 145
   at Apollo.Components.LaunchpadGrid.MouseMove(Object sender, PointerEventArgs e) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Components\LaunchpadGrid.cs:line 158
   at Apollo.Components.LaunchpadGrid.MouseDown(Object sender, PointerPressedEventArgs e) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Components\LaunchpadGrid.cs:line 126
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 192
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 156
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in D:\a\1\s\src\Avalonia.Interactivity\Interactive.cs:line 141
   at Avalonia.Input.MouseDevice.MouseDown(IMouseDevice device, UInt64 timestamp, IInputElement root, Point p, MouseButton button, InputModifiers inputModifiers) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 204
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in D:\a\1\s\src\Avalonia.Input\MouseDevice.cs:line 122
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in D:\a\1\s\src\Avalonia.Input\InputManager.cs:line 39
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in D:\a\1\s\src\Windows\Avalonia.Win32\WindowImpl.cs:line 697
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Windows\Avalonia.Win32\Win32Platform.cs:line 114
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Application.Run(Window mainWindow) in D:\a\1\s\src\Avalonia.Controls\Application.cs:line 237
   at Apollo.Core.Program.Main(String[] args) in C:\Users\Andrzej\Documents\GitHub\apollo-studio\Apollo\Core\Program.cs:line 93`

Same steps to reproduce.
Windows 10 (1803)
Apollo Build 12 (0100506)

**Comment by mat1jaczyyy** [comment]
This is a different issue, please log it separately.

**Comment by mat1jaczyyy** [comment]
Fixed in ef1ac57.
